### ISSUE TITLE
Data Set of user added cards.

### ISSUE THREAD

**Issue by JonathanCannella** [chilliard99/CEN3031#13]
As a developer I want to create a back end data structure holding cards that were added on the front end so we can see which cards have been taken out of the deck in order to calculate the probability of hands.

**Comment by TimBeavers** [comment]
Commit a6bb2f2f0328ede7903bb3c96c187d15b8a448d3 sets up key functions for sending information between ends for the hand.

**Comment by TimBeavers** [comment]
Commit 436df68746b9cfd30817243d647e22d8c07318ef implemented RemoveCards function to take an array of cards out of the deck for probability calculations.

**Comment by TimBeavers** [comment]
Commit fdbdf4add8153f1d37fa260c3022a26217192724 allows for sending an array of cards from the frontend to the backend.

**Comment by TimBeavers** [comment]
Commit ccaa25053757b074f1c2a72f141dc908f4232878 makes minor API changes following the above commit and finishes setting up the backend to receive and use the array of cards.

**Comment by TimBeavers** [comment]
Video demonstrates an array being input on the front end, being received on the backend, running the royal flush check (which successfully removes the cards from the stored deck object), and returns whether or not the hand contains a royal flush with its probability (currently only 0 or 100% as the probability logic has not been implemented correctly yet).

https://user-images.githubusercontent.com/58759497/221695939-03576283-e967-4e81-a2f9-54db161465a0.mp4
