### ISSUE TITLE
Unit tests for data structures

### ISSUE THREAD

**Issue by linelijah3** [chilliard99/CEN3031#8]
As a developer, I'd like to write unit tests for each data structure so that we can see if they are working as intended.

**Comment by linelijah3** [comment]
Basic unit tests for the hand and deck structures are complete for now as of commit 797f96e8faddaa83b75716f215605acaa3c53792 but as we expand the program, more tests will be needed, so I'm leaving this issue open for now.

**Comment by TimBeavers** [comment]
See issue #1
